language: node_js
node: 13.11.0
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run test
before_deploy:
  - npm install netlify-cli -g
  - npm run build
deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE --auth $NETLIFY_AUTH -p --dir ./build
  cleanup: false
notifications:
  slack: code-soul:onWWUFlZgoIoYyB2mPcMo66e
