language: node_js
node: 13.11.0
install:
  - npm install
script:
  - npm run build
deploy:
  provider: netlify
  site: test
  dir: ./build
  cleanup: false
notifications:
  slack: code-soul:onWWUFlZgoIoYyB2mPcMo66e
