language: node_js
node: 13.11.0
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run build
before_deploy:
  - npm install netlify-cli -g
deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE -t $NETLIFY_AUTH -p ./build
  cleanup: false
notifications:
  slack: code-soul:onWWUFlZgoIoYyB2mPcMo66e
