language: node_js
node: 13.11.0
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run test
before_deploy:
  - npm install netlify-cli -g
  - npm run build
  - ls -l
deploy:
  provider: script
  script:
    - ls -l
    - netlify deploy -s $NETLIFY_SITE --auth $NETLIFY_AUTH --prod --dir ./build
  skip_cleanup: true
notifications:
  slack: code-soul:onWWUFlZgoIoYyB2mPcMo66e
